[package]
name = "rbl-anlz"
autoexamples = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Reader for rekordbox ANLZ analysis files (.DAT/.EXT/.2EX)."

[lints]
workspace = true

[dependencies]
rbl-core = { path = "../rbl-core" }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
rbl-db = { path = "../rbl-db" }
tempfile = "3"
dirs = "5"
